//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HowItLooks.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HowItLooks.Resources.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати істоту.
        /// </summary>
        public static string AddACreature {
            get {
                return ResourceManager.GetString("AddACreature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати монстра.
        /// </summary>
        public static string AddAMonster {
            get {
                return ResourceManager.GetString("AddAMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моя програма.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клас броні.
        /// </summary>
        public static string ArmorClass {
            get {
                return ResourceManager.GetString("ArmorClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити тип істоти.
        /// </summary>
        public static string ChangeCreatureType {
            get {
                return ResourceManager.GetString("ChangeCreatureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити НР.
        /// </summary>
        public static string ChangeHP {
            get {
                return ResourceManager.GetString("ChangeHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зміна імені.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зміна ініціативи.
        /// </summary>
        public static string ChangeOfInitiative {
            get {
                return ResourceManager.GetString("ChangeOfInitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зміна звичайного HP.
        /// </summary>
        public static string ChangeRegularHP {
            get {
                return ResourceManager.GetString("ChangeRegularHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зміна тимчасового HP.
        /// </summary>
        public static string ChangeTempHP {
            get {
                return ResourceManager.GetString("ChangeTempHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть тип істоти.
        /// </summary>
        public static string ChooseCreatureType {
            get {
                return ResourceManager.GetString("ChooseCreatureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кінець.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть новий КБ.
        /// </summary>
        public static string EnterNewAC {
            get {
                return ResourceManager.GetString("EnterNewAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкажіть нове число ініціативи:.
        /// </summary>
        public static string EnterNewInitiative {
            get {
                return ResourceManager.GetString("EnterNewInitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глобальні.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На скільки змінити НР?.
        /// </summary>
        public static string HowMuchToChangeHP {
            get {
                return ResourceManager.GetString("HowMuchToChangeHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На скільки змінити тимчасові НР?.
        /// </summary>
        public static string HowMuchToChangeTempHP {
            get {
                return ResourceManager.GetString("HowMuchToChangeTempHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На скільки збільшити НР?.
        /// </summary>
        public static string HowMuchToIncreaseTheHP {
            get {
                return ResourceManager.GetString("HowMuchToIncreaseTheHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На скільки зменшити НР?.
        /// </summary>
        public static string HowMuchToReduceTheHP {
            get {
                return ResourceManager.GetString("HowMuchToReduceTheHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збільшити НР.
        /// </summary>
        public static string IncreaseTheHP {
            get {
                return ResourceManager.GetString("IncreaseTheHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основна.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назвіть істоту:.
        /// </summary>
        public static string NameTheCreature {
            get {
                return ResourceManager.GetString("NameTheCreature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назвіть монстра:.
        /// </summary>
        public static string NameTheMonster {
            get {
                return ResourceManager.GetString("NameTheMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наступний.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попередній.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зменшити НР.
        /// </summary>
        public static string ReduceHP {
            get {
                return ResourceManager.GetString("ReduceHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалення.
        /// </summary>
        public static string Removal {
            get {
                return ResourceManager.GetString("Removal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дійсно бажаєте видалити монстра?.
        /// </summary>
        public static string RemoveTheMonster {
            get {
                return ResourceManager.GetString("RemoveTheMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раунд: {0}.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почати.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На яке ім&apos;я ви його зміните?.
        /// </summary>
        public static string WhatNameWillYouChange {
            get {
                return ResourceManager.GetString("WhatNameWillYouChange", resourceCulture);
            }
        }
    }
}
