name: Build Android APK

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  vars:
    runs-on: windows-latest
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    # Restore workloads
    - name: Restore workloads
      run: dotnet workload restore

    # Install workload
    - name: Install workload
      run: dotnet workload install maui

    # Publish APK
    - name: Publish APK
      run: dotnet publish -f:net9.0-android -c Release -o ./output

    # Upload APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: ./output/HowItLooks.apk
